Homework2: Elena Rybina
dmitrysadovskii/QAP10 pull request #10
Opened 2022-09-23 05:17 UTC by rybalena

2022-09-24 10:56 UTC, dmitrysadovskii commented
Проверка на pep8 не пройдена. Посмотри логи Lint. Если возникнут вопросы - пиши в общий чат. Помогу разобраться.
![image](https://user-images.githubusercontent.com/48434081/192094121-2e123781-56d1-441a-8aa7-42fbeddc6753.png)

2022-09-24 10:57 UTC, dmitrysadovskii commented on Elena Rybina/hw2/Elena_Rybina.py
> +print("I have a great teacher Dmitry!")
))))

2022-09-24 23:15 UTC, rybalena commented
Upgrade flake8, send the same file

2022-09-25 15:42 UTC, dmitrysadovskii commented
Лена, все так же ругается на то что нет новой строки в конце файла. GitHub тоже подсказывает об этой ошибке.
![image](https://user-images.githubusercontent.com/48434081/192152256-0a314b7a-a31d-43b4-a360-5da3b3cd7045.png)

2022-09-25 15:43 UTC, dmitrysadovskii requested changes
Добавить исправление на которые ругается Lint.

2022-09-25 16:31 UTC, dmitrysadovskii approved these changes

2022-09-25 16:31 UTC, dmitrysadovskii commented on Elena Rybina/hm_2/Elena_Rybina.py
> +print("Hi!")
Эх, прошлое сообщение нравилось больше((
но главное, что все проверки прошли и можно мержить)

2022-09-25 16:31 UTC, merged

2022-09-25 16:42 UTC, rybalena commented on Elena Rybina/hm_2/Elena_Rybina.py
> +print("Hi!")
Хаха...спасибо Дима!)))