Alesia Kurylenka: Homework10
dmitrysadovskii/QAP10 pull request #102
Opened 2022-11-02 18:13 UTC by akurylenka

2022-11-05 09:14 UTC, dmitrysadovskii requested changes
Хорошая домашка. Оставь только файлы которые относятся к домаке и можно мержить

2022-11-05 09:14 UTC, dmitrysadovskii commented on Alesia Kurylenka/hw_10/task_10_1.py
> +    def find_flower(self, flower):
Если Мы говорим об бинарных операциях (аля присутствует что-то или нет) то лучше возвращать True/False

2022-11-05 09:14 UTC, dmitrysadovskii commented on Alesia Kurylenka/hw_10/task_10_1.py
> +        assert param in ['name', 'freshness_days', 'color', 'stem_length', 'price'], "There is no such param"
like

2022-11-06 19:06 UTC, akurylenka commented on Alesia Kurylenka/hw_10/task_10_1.py
> +        assert param in ['name', 'freshness_days', 'color', 'stem_length', 'price'], "There is no such param"
@dmitrysadovskii  fixed, please check)

2022-11-07 08:11 UTC, merged