Alesia Kurylenka: Homework11
dmitrysadovskii/QAP10 pull request #104
Opened 2022-11-02 18:30 UTC by akurylenka

2022-11-05 09:12 UTC, dmitrysadovskii requested changes
Подправь комменты и в PR должны быть только файлы относящиеся к домашке. Убери лишнее.

2022-11-05 09:12 UTC, dmitrysadovskii commented on Alesia Kurylenka/hw_11/main.py
> +            raise print("Numbers should be integer or float")
Ты должна рейсись ошибку, а не принт. Сообщение об ошибке может быть передеанно в объект ошибки TypeError("Алеся, пиши сообщение об ошибки сюда")

В данном случае можно добавить 2 ассерта на проверку типов

2022-11-05 09:12 UTC, dmitrysadovskii commented on Alesia Kurylenka/hw_11/main.py
> +        return print(f"Your addition result: {number1 + number2}")
print() возвращает None, поэтому Тебе нету смысла его возвращать

2022-11-06 18:51 UTC, akurylenka commented on Alesia Kurylenka/hw_11/main.py
> +            raise print("Numbers should be integer or float")
fixed

2022-11-06 18:52 UTC, akurylenka commented on Alesia Kurylenka/hw_11/main.py
> +        return print(f"Your addition result: {number1 + number2}")
fixed

2022-11-06 19:06 UTC, akurylenka commented on Alesia Kurylenka/hw_11/main.py
> +        return print(f"Your addition result: {number1 + number2}")
@dmitrysadovskii  fixed, please check)

2022-11-07 08:10 UTC, merged