Elena Rybina: Homework 6
dmitrysadovskii/QAP10 pull request #110
Opened 2022-11-07 07:46 UTC by rybalena

2022-11-07 08:16 UTC, dmitrysadovskii requested changes
Зачем Ты удалила файл Оли?)
Верни его обратно и подправь коммент

2022-11-07 08:16 UTC, dmitrysadovskii commented on Elena Rybina/hw_6/task_6_3.py
> +    else:
Этот else не несет никакой смысловой нагрузки поэтому можно его убрать

2022-11-07 08:18 UTC, rybalena commented on Elena Rybina/hw_6/task_6_3.py
> +    else:
я нечаянно  удалила на локалке(

2022-11-08 07:48 UTC, rybalena commented on Elena Rybina/hw_6/task_6_3.py
> +    else:
я не понимаю в чем ошибка

2022-11-10 05:30 UTC, merged