add homework4
dmitrysadovskii/QAP10 pull request #14
Opened 2022-09-24 18:47 UTC by Shadowman405

please check HW-4

2022-09-25 15:26 UTC, dmitrysadovskii commented
Проверка на pep8 не пройдена
![image](https://user-images.githubusercontent.com/48434081/192151541-0c78471b-cf66-49f5-a759-668c42e0e779.png)

2022-09-25 15:27 UTC, dmitrysadovskii requested changes
Исправить проверки на pep8. 
После этого можно будет приступать смотреть PR.

2022-09-26 21:53 UTC, Shadowman405 commented
вроде поправил, чеки плз

2022-09-29 00:49 UTC, dmitrysadovskii commented
Проверки lint все ещё не проходят.
Посмотри логи lint, там указано в каком файле, на какой строчке и что нужно исправить.

![image](https://user-images.githubusercontent.com/48434081/192913586-7b31f650-1eec-4eac-a68b-28a17c975e13.png)

2022-09-29 20:08 UTC, Shadowman405 commented
fix

2022-10-06 11:16 UTC, dmitrysadovskii commented
Данные файлы и папки необходимо добавить в  gitingnore файл и можно будет мержить домашку
![image](https://user-images.githubusercontent.com/48434081/194299407-2775be63-27a1-472f-b6b8-f0a3eb5e2d55.png)

2022-10-06 20:11 UTC, Shadowman405 commented
я не понимаю, на уровне выше моей папки есть гитигнор и в нем есть в исключениях папка .idea/
, как она попадает в пул реквестору

2022-10-08 11:35 UTC, dmitrysadovskii commented
Напиши в телегу. Договоримся о времени что бы вместе глянуть.

2022-10-15 18:51 UTC, merged