Alesia Kurylenka: Homework4
dmitrysadovskii/QAP10 pull request #16
Opened 2022-09-25 11:25 UTC by akurylenka

2022-09-25 15:22 UTC, dmitrysadovskii requested changes

2022-09-25 15:22 UTC, dmitrysadovskii commented on Alesia Kurylenka/hm_4/task_4_5.py
> +    dict_3[k] = [dict_1.get(k), dict_2.get(k)]
Посмотри как сделать через генератор словарей

2022-09-25 15:22 UTC, dmitrysadovskii commented on Alesia Kurylenka/hm_4/task_4_6.py
> +        print(i)
Посмотри как сделать через генератор списков

2022-09-25 15:22 UTC, dmitrysadovskii commented on Alesia Kurylenka/hm_4/task_4_6.py
> +a = [1, 5, 2, 9, 2, 9, 1]
Давай переменным имена, которые отражают находящуися в них данные

2022-09-25 15:22 UTC, dmitrysadovskii commented on Alesia Kurylenka/hm_4/task_4_7.py
> +a1 = (''.join(filter(str.isalpha, a)))
Почему Ты решила использовать здесь фильтр и что такое str.isalpha?

2022-09-25 17:40 UTC, akurylenka commented on Alesia Kurylenka/hm_4/task_4_7.py
> +a1 = (''.join(filter(str.isalpha, a)))
через filter мы оставляем только True значения, 
которые были проверены методом str.isalpha() является ли символ в строке буквой = True или если нет - то False

2022-09-26 15:13 UTC, dmitrysadovskii requested changes

2022-09-26 15:13 UTC, dmitrysadovskii commented on Alesia Kurylenka/hm_4/task_4_6.py
> +#         print(i)
Тоже самое что выше.

2022-09-29 00:55 UTC, merged