Files for home work 3
dmitrysadovskii/QAP10 pull request #18
Opened 2022-09-25 13:09 UTC by verygnawtyatwork

Please check my home work 3.

2022-09-25 15:15 UTC, dmitrysadovskii requested changes
Подправь комментарий и можно будет мержить.

2022-09-25 15:15 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_3/task_3_3.py
> +# Хотя со split() присвоение работает
Для того, что бы ответить на этот вопрос нужно посмотреть у какого типа данных вызывается команда reverse().
и что будет содержится в переменной test_string = test_string.split()

2022-09-25 15:15 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_3/task_3_4.py
> +new_string = test_string[1:(len(test_string) - 1)]
Для того, что бы указать срез с первого до последнего элемента не включительно используется [1:-1]. Так как -1  - это последний элемент последовательности.

2022-09-25 18:25 UTC, verygnawtyatwork commented
Correction of mistakes

2022-09-26 15:11 UTC, dmitrysadovskii commented
Указывай в заголовке PR имя и фамилию, что бы было понятно кому защитывать домашку.
В остальном все хорошо. Можно мержить)

2022-09-26 16:02 UTC, verygnawtyatwork commented
Вот мои данные: Евгений Споршев.

2022-09-29 00:44 UTC, dmitrysadovskii approved these changes

2022-09-29 00:44 UTC, merged