Homework 3: Rybina Elena
dmitrysadovskii/QAP10 pull request #23
Opened 2022-09-26 01:00 UTC by rybalena

2022-09-29 01:01 UTC, dmitrysadovskii commented
1 PR = 1 домашняя работа.
Раздели 3 и 4 домашку по разным PR.

2022-10-06 11:14 UTC, dmitrysadovskii requested changes

2022-10-06 11:14 UTC, dmitrysadovskii commented on .gitignore
> -.idea/
Почему Ты все удалила в этом файле?

2022-10-06 17:43 UTC, rybalena commented on .gitignore
> -.idea/
я его удалила уже в GitHub

2022-10-08 11:33 UTC, dmitrysadovskii requested changes

2022-10-08 11:33 UTC, dmitrysadovskii commented on .gitignore
> -# Byte-compiled / optimized / DLL files
Не нужно удалять содержимое файла .gitignore
Напиши Мне в личку в телеге. Договоримся о времени и вместес этим разберёмся.

2022-10-10 00:48 UTC, closed without merging