Homework4
dmitrysadovskii/QAP10 pull request #24
Opened 2022-09-27 13:11 UTC by Raikhelson

2022-09-29 01:11 UTC, dmitrysadovskii commented
1 PR = 1 домашнее задание.
Разбить домашки по разным PR

2022-09-29 01:17 UTC, dmitrysadovskii commented
Проверки Lint не прошли. Необходимо посмотреть логи проверки. Там будет указан файл, номер строки и наименование ошибки.

![image](https://user-images.githubusercontent.com/48434081/192916115-7d5e1458-f93f-4a26-a525-b66e6208ecd3.png)

2022-09-29 01:17 UTC, dmitrysadovskii requested changes

2022-09-29 01:17 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_4/task_4_5.py
> +for k, v in b.items():
Объедений 2 словаря и пройдись по его ключам. Бери значение ключа для словарей a и b через метод get().

2022-09-29 01:17 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_4/task_4_6.py
> +    if count == min(el_count.values()):
Если уникального числа в списке не будет, то у Тебя min value будет следующего, который минимальное колосовой раз встречается, но это будет не число, которое встречается один раз.

2022-09-29 01:17 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +reg = re.compile('[^a-zA-Z ]')
Что означает данное регулярное выражение?

2022-09-29 01:17 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +reg = re.compile('[^a-zA-Z ]')
Что означает данное регулярное выражение?

2022-09-29 01:17 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +text_from_let = sorted(reg.sub('', text).replace(' ', '').lower())
Что в данной конструкции выполняет sub()?

2022-09-29 01:17 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +text_from_let = sorted(reg.sub('', text).replace(' ', '').lower())
Что в данной конструкции выполняет sub()?

2022-09-29 10:16 UTC, Raikhelson commented
> PR = 1 д

тобишь нужно сделать измения в коде. снова сделать  коммит  и сделать pull? я правильно понима.

2022-09-29 10:29 UTC, Raikhelson commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +reg = re.compile('[^a-zA-Z ]')
То что в этот диапазон НЕ входят все символы от a до z и от A до Z?

2022-10-05 12:25 UTC, Raikhelson commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +reg = re.compile('[^a-zA-Z ]')
найди  то  что  не входит  в диапазон от a до z и от A до Z

2022-10-05 12:29 UTC, Raikhelson commented on Valerie_Raikhelson/hm_4/task_4_7.py
> +text_from_let = sorted(reg.sub('', text).replace(' ', '').lower())
возвращает новую строку  после того как был  выполнен поиск символов не входящих  в диапазон от a до z и от A до Z

2022-10-06 11:12 UTC, dmitrysadovskii commented
Необходимо решить конфликт. Сегодня сделаем это вместе перед началом занятия.
![image](https://user-images.githubusercontent.com/48434081/194298716-667cc750-752c-4373-a1db-df04e472bbef.png)

2022-10-07 13:11 UTC, Raikhelson commented on Valerie_Raikhelson/hm_4/task_4_5.py
> +for k, v in b.items():
исправлено

2022-10-07 13:12 UTC, Raikhelson commented
я не знаю что делать здесь

2022-10-08 12:32 UTC, dmitrysadovskii commented
Напомни перед занятием, что бы Мы вместе решилики конфликт в данном PR

2022-10-12 11:35 UTC, merged