Evgeny sporshev homework4
dmitrysadovskii/QAP10 pull request #25
Opened 2022-09-28 11:33 UTC by verygnawtyatwork

Просьба так же посмотреть домашнее задание 3: https://github.com/dmitrysadovskii/QAP10/pull/18
А то в табличке выполнения ДЗ оно у меня не отмечена.

2022-09-29 00:40 UTC, dmitrysadovskii commented
В 4 дз должны быть задания только по 4 дз.

2022-09-29 00:41 UTC, dmitrysadovskii requested changes

2022-09-29 00:41 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_4/task_4_5.py
> +        ab.update({k: [a[k], b[k]]})
Значение ключей можно извлекать при помощи get() функции. Подумай как можно реализовать через неё.

2022-10-02 17:51 UTC, dmitrysadovskii requested changes
Разнести домшки 3 и 4 по разным PR

2022-10-03 10:00 UTC, verygnawtyatwork commented
https://github.com/dmitrysadovskii/QAP10/pull/25#pullrequestreview-112767482229.09.2022, 03:41, "dmitrysadovskii" ***@***.***>:
@dmitrysadovskii requested changes on this pull request.



In Evgeny Sporshev/hw_4/task_4_5.py:
> @@ -0,0 +1,14 @@
+a = {'a': 1, 'b': 2, 'c': 3}
+b = {'c': 3, 'd': 4, 'e': 5}
+ab = {}
+# ab = {'a': [1, None], 'b': [2, None], 'c': [3, 3], 'd': [None, 4], 'e': [None, 5]}
+
+for k, v in {**a, **b}.items():
+    if k in a and k in b:
+        ab.update({k: [a[k], b[k]]})

Значение ключей можно извлекать при помощи get() функции. Подумай как можно реализовать через неё.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-06 11:10 UTC, merged