add homework3
dmitrysadovskii/QAP10 pull request #26
Opened 2022-09-28 16:24 UTC by SergeyZapashchykov

Sergey_Zapashchykov: Homework_3

2022-09-29 01:22 UTC, dmitrysadovskii requested changes

2022-09-29 01:22 UTC, dmitrysadovskii commented on Sergey Zapashchykov/HW_3/task_3_2.py
> +    print((f'{word}ing'), end=' ')
Если word будет "Dzmitry Sadouski", то программа будет работать не корректно.
Должно бать "Dzmitrying Sadouskiing"

2022-09-29 20:38 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_3/task_3_2.py
> +    print((f'{word}ing'), end=' ')
Дмитрий, не совсем понимаю почему будет работать некорректно - я же сначала разделю мою введенную строку в список по признаку пробела, а потом каждый элемент списка буду обрабатывать и добавлять окончание "ing".
Можете пояснить. если не затруднит?

2022-09-29 21:10 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_3/task_3_2.py
> +    print((f'{word}ing'), end=' ')
Поправил task_3_2.
Попробовал без цикла сделать.

2022-09-30 04:15 UTC, SergeyZapashchykov commented
Поправил task_3_2.

2022-10-01 07:59 UTC, dmitrysadovskii approved these changes

2022-10-01 08:00 UTC, merged