Valeria Kondrateva: homework 3 and 4
dmitrysadovskii/QAP10 pull request #27
Opened 2022-09-28 19:43 UTC by llleeera

2022-09-29 01:30 UTC, dmitrysadovskii requested changes
Хорошее дз)
1 PR = 1 домашняя работа. Разбей домашки 3,4 по разным PR и можно мержить.

2022-09-29 09:53 UTC, llleeera commented
Разделила. Homework 3 по ссылке: https://github.com/dmitrysadovskii/QAP10/pull/21
Каждое ДЗ нужно делать в отдельной ветке? Или ветка остается одна и в ней создаю папки с дз?

2022-09-29 10:07 UTC, llleeera commented
> Хорошее дз) 1 PR = 1 домашняя работа. Разбей домашки 3,4 по разным PR и можно мержить.

Разделила. Homework 3 по ссылке: https://github.com/dmitrysadovskii/QAP10/pull/21
Каждое ДЗ нужно делать в отдельной ветке? Или ветка остается одна и в ней создаю папки с дз?

2022-10-01 08:02 UTC, dmitrysadovskii commented
Все верно. Каждое дз в новой ветки.

2022-10-02 17:49 UTC, merged