Evgeny Sporshev Homework 5
dmitrysadovskii/QAP10 pull request #34
Opened 2022-10-03 23:24 UTC by verygnawtyatwork

PLease, check it.

2022-10-06 11:03 UTC, dmitrysadovskii requested changes

2022-10-06 11:03 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_5/task_5_1.py
> +if likes_list == []:
проверяй по длине что список пустой, так как в дальнейшем Ты проверяешь на длину. Сохраняй один стиль проверок.

2022-10-06 11:03 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_5/task_5_1.py
> +    if likes_list[0][0].lower() in russian_letters:
Сделай верхнеуровневую проверку по языку и тогда Тебе не придется в каждом блоке if/elif проверять на язык

2022-10-06 11:03 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_5/task_5_3.py
> +secret_number = input('Игрок 1, загадай четырехзначное число число: ')
игрок имеет возможность ввести число состоящее более чем из 4 повторяющихся цифр и ответить числом состоящим не из 4 цифр
![image](https://user-images.githubusercontent.com/48434081/194297066-cc6b077f-6a66-4e6b-a1b4-e2f3613e1285.png)

2022-10-06 11:04 UTC, dmitrysadovskii requested changes

2022-10-06 11:04 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_5/task_5_1.py
> +russian_letters = ['й', 'ц', 'у', 'к', 'е', 'н', 'г', 'ш', 'щ', 'з', 'х', 'ъ', 'ф', 'ы', 'в', 'а', 'п', 'р', 'о', 'л',
Посмотри  что такое ascii и как это можно использовать в данной задаче

2022-10-07 15:29 UTC, verygnawtyatwork commented
Просьба проверить - исправил task_5.1 и task_5.3

2022-10-09 17:04 UTC, verygnawtyatwork commented
Просьба проверить.

2022-10-12 11:13 UTC, merged