Homework5
dmitrysadovskii/QAP10 pull request #43
Opened 2022-10-05 16:57 UTC by Raikhelson

2022-10-06 10:34 UTC, dmitrysadovskii requested changes

2022-10-06 10:34 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_5/task_5_2.py
> +        continue
Используй if/elif/else и тогда не придется использовать continue

2022-10-06 10:34 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_5/task_5_3.py
> +import random
Пользователь может ввести 5-ти значное число с повторяющимся цифрами
![image](https://user-images.githubusercontent.com/48434081/194291340-12803a63-c203-46ed-8159-3a15cdd8266d.png)

2022-10-06 10:34 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_5/task_5_3.py
> +number = int("".join(map(str, list(digits))))
Зачем Ты делаешь преобразование digits к list?

2022-10-06 10:34 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_5/task_5_3.py
> +list_of_hid_num = list(map(int, str(hidden_num)))
Зачем преорабзовываешь hidden_num к str, если это и так будет тип данных str.

2022-10-06 10:35 UTC, dmitrysadovskii commented
не пройдена проверка на pep8
![image](https://user-images.githubusercontent.com/48434081/194291902-9e6a0207-45f5-4efb-9de0-f05c0d545f72.png)

2022-10-07 13:08 UTC, Raikhelson commented on Valerie_Raikhelson/hm_5/task_5_2.py
> +        continue
исправлено

2022-10-07 13:09 UTC, Raikhelson commented on Valerie_Raikhelson/hm_5/task_5_3.py
> +import random
исправлено

2022-10-07 13:09 UTC, Raikhelson commented on Valerie_Raikhelson/hm_5/task_5_3.py
> +number = int("".join(map(str, list(digits))))
исправлено

2022-10-07 13:09 UTC, Raikhelson commented on Valerie_Raikhelson/hm_5/task_5_3.py
> +list_of_hid_num = list(map(int, str(hidden_num)))
исправлено

2022-10-08 12:31 UTC, dmitrysadovskii commented
Напомни, пожалуйста, что бы перед занятием с Тобой пофиксили конфлик в данном PR.
Остальное хорошо, можно мержить

2022-10-14 20:56 UTC, Raikhelson commented
<img width="878" alt="image" src="https://user-images.githubusercontent.com/114160353/195942373-635ac77e-74f5-4995-abf7-7d8f8dba981e.png">

Дима привет. я не вижу 'resolve conflict' ....

2022-10-15 18:53 UTC, dmitrysadovskii commented
Напомни, в пн в перерыве сделаем еще раз вместе

2022-10-17 21:46 UTC, Raikhelson commented
исправлено

2022-10-18 14:32 UTC, merged