Homework5
dmitrysadovskii/QAP10 pull request #48
Opened 2022-10-06 20:35 UTC by Shadowman405

add homework 5 and .gitignore

2022-10-08 12:14 UTC, dmitrysadovskii requested changes
1 PR = 1 домашняя работа.

2022-10-08 12:14 UTC, dmitrysadovskii commented on Maksim_Mitin/hw_5/task_5_3.py
> +import random
Неверный подсчет коров и быков
![image](https://user-images.githubusercontent.com/48434081/194706899-50641f7c-cab1-45c8-b300-e662ffed3f39.png)
![image](https://user-images.githubusercontent.com/48434081/194706931-7dede781-8b17-47de-bb30-01f24e7cd432.png)

Игрок может ввести число состоящее и повторяющихся цифр и число, которое больше 4 цифр
![image](https://user-images.githubusercontent.com/48434081/194706979-a0feb74f-eb9d-4fac-9490-015249028e4f.png)

2022-10-16 13:50 UTC, Shadowman405 commented
у меня после вчерашних наших манипуляций пропали файлы 5 домашку переделал все с нуля

2022-10-18 14:33 UTC, dmitrysadovskii commented
Необходимо зарезолвить конфликты
![image](https://user-images.githubusercontent.com/48434081/196460418-fa4cc794-1345-44dd-a629-6c8ed45e5dab.png)

2022-10-20 20:30 UTC, Shadowman405 commented
вроде нет у меня нет такого файла , свичнулся на эту ветку и не нашел

2022-11-07 08:10 UTC, dmitrysadovskii commented
Дубликат
https://github.com/dmitrysadovskii/QAP10/pull/107/files

2022-11-07 08:10 UTC, closed without merging