Ekaterina Prishutova: homework 6
dmitrysadovskii/QAP10 pull request #50
Opened 2022-10-07 12:02 UTC by katiprishutova

2022-10-08 12:30 UTC, dmitrysadovskii requested changes
В общем все хорошо, подправь замечания и можно мержить

2022-10-08 12:30 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_6/task_6_3.py
> +    except ValueError:
Посмотри как работает фукнция isinstance() это поможет Тебе избавиться от try/except вырожения здесь

2022-10-08 12:30 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_6/task_6_3.py
> +            if operation == "4":
данную проверку лучше вынести на 16 строчку где происходит деление. Это разгрузит if блок и будет держать валидуцию чисел для деления поближе к самое операции деления, что интуитивно будет понятно что происходит и не нужно будет бегать по коду и искать проверки

2022-10-09 15:28 UTC, katiprishutova commented on Ekaterina_Prishutova/hm_6/task_6_3.py
> +    except ValueError:
Не очень поняла как оно поможет, ибо input читает строку, а чтобы проверить на тип нужно конвертировать, ошибочная конвертация даст ошибку

2022-10-09 15:29 UTC, katiprishutova commented
Поправила замечание с проверкой на 0, по второму отписалась, не придумала как его использовать

2022-10-12 11:20 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_6/task_6_3.py
> +    except ValueError:
Да, Ты права. Тогда можно поступить другим образом.
Сделать assert где проверим, что строка из input содержит только цифры (посмотрим метод "".isdigit()" и тогда при прохождении ассерта конвертация всегда будет верной.

2022-10-12 11:20 UTC, dmitrysadovskii requested changes
Подправь коммент и будем мержить)

2022-10-12 13:36 UTC, katiprishutova commented on Ekaterina_Prishutova/hm_6/task_6_3.py
> +    except ValueError:
В итоге просто расписала функцию со всеми возможными видами чисел(которые вспомнила)
"".isdigit()" мне не везде бы помог, ибо числом определяет только положительные целочисленные значения

2022-10-12 13:36 UTC, katiprishutova commented
done

2022-10-15 18:54 UTC, merged