homework_6
dmitrysadovskii/QAP10 pull request #51
Opened 2022-10-07 16:22 UTC by Raikhelson

2022-10-08 12:35 UTC, dmitrysadovskii requested changes

2022-10-08 12:35 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_6/task_6_3.py
> +if op == "1":
Данную конструкцию необходимо обернуть в функцию

2022-10-08 12:35 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_6/task_6_3.py
> +    except ZeroDivisionError:
Вместо try/excpect блока проверяй num_2 на то что равен 0 в assert конструкции.

2022-10-10 10:03 UTC, Raikhelson commented on Valerie_Raikhelson/hm_6/task_6_3.py
> +    except ZeroDivisionError:
исправлено

2022-10-10 10:03 UTC, Raikhelson commented on Valerie_Raikhelson/hm_6/task_6_3.py
> +if op == "1":
исправлено

2022-10-17 21:46 UTC, Raikhelson commented
исправлено

2022-10-18 14:34 UTC, merged