Homework6: Alesia Kurylenka
dmitrysadovskii/QAP10 pull request #52
Opened 2022-10-08 15:58 UTC by akurylenka

2022-10-12 19:41 UTC, dsadovsky requested changes

2022-10-12 19:41 UTC, dsadovsky commented on Alesia Kurylenka/hw_6/task_6_3.py
> +        print("please enter digits only")
Создай assert на проверку того, что number1 и number_2 содержат только цифры. Это избавит Тебя от блока if/else

2022-10-12 19:41 UTC, dsadovsky commented on Alesia Kurylenka/hw_6/task_6_3.py
> +        b = float(number2)
a и b - это буквы алфавита. У Тебя же number1 и number2, так и оставь их.
number1 = float(number1) и тоже самое для number2

2022-10-12 19:41 UTC, dsadovsky commented on Alesia Kurylenka/hw_6/task_6_3.py
> +    if user_input not in ["add", 'sub', 'mul', 'div']:
Вместо блока if/else создай assert где проверяешь, что user_input in ["add", и т.д]

2022-10-13 16:03 UTC, akurylenka commented
@dsadovsky please check the fixes

2022-10-15 18:55 UTC, merged