homework 5 added
dmitrysadovskii/QAP10 pull request #53
Opened 2022-10-08 22:51 UTC by AntonLepesiy

2022-10-12 19:50 UTC, dsadovsky requested changes

2022-10-12 19:50 UTC, dsadovsky commented on Anton Lepesiy/hw_5/task_5_1.py
> +# likes = ("Ann", "Alex", "Mark")
Удали ненужные комменты

2022-10-12 19:50 UTC, dsadovsky commented on Anton Lepesiy/hw_5/task_5_1.py
> +elif type(likes) == str:
Сохраняй идентичность проверок: везде проверяешь на количество элементов в tuple, так и тут проверяй, что в тапле 1 имя.

2022-10-12 19:50 UTC, dsadovsky commented on Anton Lepesiy/hw_5/task_5_3.py
> +import random
Пользователь имеет возможность ввести число с 4 повторяющими цифрами.
Неверный подсчет
![image](https://user-images.githubusercontent.com/104438677/195434655-60fd5550-c76f-40d6-95fa-7f85f316ab45.png)

2022-10-18 14:36 UTC, dmitrysadovskii requested changes

2022-10-20 10:20 UTC, AntonLepesiy commented on Anton Lepesiy/hw_5/task_5_1.py
> +# likes = ("Ann", "Alex", "Mark")
удалил

2022-10-20 10:23 UTC, AntonLepesiy commented on Anton Lepesiy/hw_5/task_5_1.py
> +elif type(likes) == str:
если применять к 1 имени проверку по длине, то результатом будет число  букв в имени, а не кол-во имен в массиве

2022-10-20 10:25 UTC, AntonLepesiy commented on Anton Lepesiy/hw_5/task_5_3.py
> +    if int(number_2) == int(number_1):
исправил

2022-10-20 10:25 UTC, AntonLepesiy commented on Anton Lepesiy/hw_5/task_5_3.py
> +    elif abs(int(number_2)) == 0:
удалил

2022-10-26 11:16 UTC, merged