Ekaterina Prishutova: homework 7
dmitrysadovskii/QAP10 pull request #61
Opened 2022-10-11 12:46 UTC by katiprishutova

В последнем задании не стала расписывать шифр цезаря на encode decode,  вынесла в функцию оболочку, в которой в зависимости от режима вызывается функция кодирования с соответствующими параметрами

2022-10-12 11:49 UTC, dmitrysadovskii requested changes
В общем хорошая домашняя работа. Исправь комменты и можно мержить.

2022-10-12 11:49 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_7/task_7_1.py
> +            return_matrix.append([])
Сформируй 2 списка через генератор списков, так как это простое действие и вместо 3 строк кода получится одна.

2022-10-12 11:49 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_7/task_7_1.py
> +        return None
Данную проверку сделай через assert, так Ты избавишься от if конструкции и внесёшь читаемость в код, что к Тебя идёт явная проверка условия.

2022-10-12 11:49 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_7/task_7_4.py
> +        print("Неподдерживаемый язык")
В начале функции добавь assert на проверку того, что переданный язык находится в списке ["en", "ru"]. Это избавит Тебя от ненужного if и код не будет выполняться без надобности.

2022-10-12 11:49 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_7/task_7_4.py
> +                               "".join([chr(letter) for letter in range(ord("Ж"), ord("Я") + 1)]))
Формирование lower и upper letters дублируется в первой и во второй функции. Вынеси это в отдельную функцию.

2022-10-12 11:49 UTC, dmitrysadovskii commented on Ekaterina_Prishutova/hm_7/task_7_4.py
> +        print("Некорректно выбран режим кодирования")
Проверку режима кодировки так же вынеси выше в функции в assert

2022-10-12 15:15 UTC, katiprishutova commented
Внесла правки по всем комментариям
flake8 так и не поборола, понаставила скобочки, но он все равно не рад

2022-10-15 19:09 UTC, dmitrysadovskii commented
Add W503 flake8 error to ignore

2022-10-27 19:24 UTC, katiprishutova commented
все поправила, проверки на flake8  прошли

2022-11-02 04:35 UTC, merged