Homework7
dmitrysadovskii/QAP10 pull request #62
Opened 2022-10-11 19:40 UTC by Raikhelson

2022-10-12 19:57 UTC, dmitrysadovskii commented
Убери из PR изменения по домашнему заданию 2 и 3 и пофикси конфликт. После этого можно мержить.

2022-10-12 19:57 UTC, dmitrysadovskii requested changes
Пофиксить коммент

2022-10-15 19:10 UTC, dmitrysadovskii requested changes
Все хорошо, нужно только порешать конфликты

2022-10-17 21:47 UTC, Raikhelson commented
исправлено

2022-10-18 14:37 UTC, merged