Evgeny Sporshev Homework 6
dmitrysadovskii/QAP10 pull request #63
Opened 2022-10-11 23:58 UTC by verygnawtyatwork

Please check it.

2022-10-12 00:02 UTC, verygnawtyatwork commented
Просьба проверить.

2022-10-12 11:58 UTC, dmitrysadovskii requested changes
В общем хорошо. Подправь коммент и можно мержить.

2022-10-12 11:58 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_6/hw_6_3.py
> +    # division_items = reduce(lambda x, y: x / y, items)
Удали ненужный коммент

2022-10-12 11:58 UTC, dmitrysadovskii commented on Evgeny Sporshev/hw_6/hw_6_3.py
> +        if first_number.isupper() or first_number.islower():
Можно проверить, на то что в input были введены числа isdigits()

2022-10-13 08:17 UTC, verygnawtyatwork commented
Просьба проверить.

2022-10-15 19:11 UTC, merged