Valeria Kondrateva: HW_6
dmitrysadovskii/QAP10 pull request #66
Opened 2022-10-12 11:59 UTC by llleeera

2022-10-12 12:10 UTC, dmitrysadovskii requested changes
Исправь комменты и можно мержить

2022-10-12 12:10 UTC, dmitrysadovskii commented on Valeria_Kondrateva/hw_6/task_6_1.py
> +def luhn(card):
не все карты проходят
![image](https://user-images.githubusercontent.com/48434081/195338858-00380bc4-4d43-4eff-a8a4-847e1c480708.png)

2022-10-12 12:10 UTC, dmitrysadovskii commented on Valeria_Kondrateva/hw_6/task_6_2.py
> +for key, value in count_dict.items():
Оберни решение в функцию

2022-10-12 12:10 UTC, dmitrysadovskii commented on Valeria_Kondrateva/hw_6/task_6_3.py
> +if operations == '1':
Оберни решение в функцию

2022-10-13 16:52 UTC, llleeera commented
задания исправила

2022-10-15 19:11 UTC, merged