Sergey_Zapashchykov: Homework6
dmitrysadovskii/QAP10 pull request #67
Opened 2022-10-12 21:09 UTC by SergeyZapashchykov

Задание готово к проверке.

2022-10-15 19:17 UTC, dmitrysadovskii requested changes
В общем хорошо. Подправь комменты и можно мержить.

2022-10-15 19:17 UTC, dmitrysadovskii commented on Sergey Zapashchykov/HW_6/task_6_3.py
> +    if not number_1.isdigit() or not number_2.isdigit():
Используй assert для проверки валидности данных

2022-10-15 19:17 UTC, dmitrysadovskii commented on Sergey Zapashchykov/HW_6/task_6_3.py
> +    if int(number_2) == 0 and operator == 'division':
Используй так же assert, так Ты помечаешь в коде, что проводишь проверку и получишь AssertionError если проверка не пройдет.
Вынеси данную проверку в блок if где идет деление, так как эта проверка относится именно к ней и Тебе не нужно каждый раз проверять данное условие. Ты будешь проверять это только при делении.

2022-10-18 21:17 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_6/task_6_3.py
> +    if not number_1.isdigit() or not number_2.isdigit():
Добавил assert для проверки.

2022-10-18 21:17 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_6/task_6_3.py
> +    if int(number_2) == 0 and operator == 'division':
Добавил assert для проверки.

2022-10-26 11:20 UTC, merged