Valeria Kondrateva:Homework7
dmitrysadovskii/QAP10 pull request #68
Opened 2022-10-13 21:23 UTC by llleeera

2022-10-13 21:24 UTC, llleeera commented
mistake

2022-10-15 19:18 UTC, dmitrysadovskii commented
Необходимо решить конфликт в PR.
Напомни в пн, что бы показал как.

2022-10-15 19:19 UTC, dmitrysadovskii requested changes
Все хорошо, домашка принята. Нужно только пофиксить конлфикты.

2022-10-17 18:20 UTC, llleeera commented
конфликт исправлен

2022-10-18 14:38 UTC, merged