Dmitry_Gorski: Homework 8
dmitrysadovskii/QAP10 pull request #69
Opened 2022-10-14 06:18 UTC by dgorski82

По задаче с калькулятором не стал сильно заморачиваться... Решение работает, засчитывать его или нет - решать Вам.

2022-10-15 19:29 UTC, dmitrysadovskii requested changes

2022-10-15 19:29 UTC, dmitrysadovskii commented on Dmitry_Gorski/hw_8/task_8_3.py
> +        return eval(a)
eval - это троянский конь, который готов сжечь себя не доехав до места назначения. 
eval выполняет любое строчное выражение и так как нет никак валидации данных, то Ты можешь словить очень много разных ошибок. Добавь валидацию данных перед тем как будет вызывать eval.

2022-10-15 19:29 UTC, dmitrysadovskii commented on Dmitry_Gorski/hw_8/task_8_3.py
> +        return eval(a)
Декоратором можешь сделать валидатор значений и повесить на функции выполняющие математические операции.

2022-10-17 06:53 UTC, dgorski82 commented on Dmitry_Gorski/hw_8/task_8_3.py
> +        return eval(a)
Изменения внесены!

2022-10-18 14:40 UTC, dmitrysadovskii approved these changes
Одна небольшая ремарка, поэтому можешь не переделывать. Задание принято.

2022-10-18 14:40 UTC, dmitrysadovskii commented on Dmitry_Gorski/hw_8/task_8_3.py
> +    if all([i.isdigit() or i in ('+', '-', '/', '%', '//', '**') for i in string.replace(' ', '')]):
Тебе нет смысла здесь делать if/else блок, так как Ты можешь данную проверку вынести в assert и сообщение об ошибка написать "Это не математическое выражение"
После assert сделать eval

2022-10-18 14:40 UTC, merged