Homework8
dmitrysadovskii/QAP10 pull request #70
Opened 2022-10-14 20:28 UTC by Raikhelson

2022-10-15 19:41 UTC, dmitrysadovskii requested changes

2022-10-15 19:41 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_8/task_8_1.py
> +            if type == 'int':
Почему Ты решила использовать if, а не elif?

2022-10-15 19:41 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_8/task_8_1.py
> +                func(sum(map(float, args)))
В блоке if можешь провести преобразование данных и после блока if вызвать функцию с уже пробразованными данными.
if type == "str":
  convert_args = "".join()
elif type == "int":
  convert_args = "".join()
func(convert_args)

2022-10-15 19:41 UTC, dmitrysadovskii commented on Valerie_Raikhelson/hm_8/task_8_2.py
> +from num2words import num2words
Тебе необходимо реализовать функцию, которая будет на вход принимать неограниченное число аргументов в виде чисел от 0 до 19 и выводить в консоль их в сортированом порядке как в англ алфавите.

Сортировку числе как раз и должен делать декоратор

def sort_numbers(func):
  def wrapper(*args):
      func()
  
 @sort_numbers
 def print_sort_numbers(*args):
     pinr(args) # 1, 3, 2
     
 print_sort_numbers(1, 2, 3)

2022-10-16 13:26 UTC, Raikhelson commented on Valerie_Raikhelson/hm_8/task_8_2.py
> +from num2words import num2words
исправлено

2022-10-16 13:27 UTC, Raikhelson commented on Valerie_Raikhelson/hm_8/task_8_1.py
> +                func(sum(map(float, args)))
исправлено

2022-10-16 13:27 UTC, Raikhelson commented on Valerie_Raikhelson/hm_8/task_8_1.py
> +            if type == 'int':
исправила. просто так нравится ))))

2022-10-17 21:47 UTC, Raikhelson commented
исправлено

2022-10-18 14:41 UTC, merged