Valeria Kondrateva: HW_9
dmitrysadovskii/QAP10 pull request #94
Opened 2022-10-25 06:29 UTC by llleeera

2022-11-02 09:07 UTC, dmitrysadovskii requested changes
Хорошая домашка. Подправь комменты и можно мержить)

2022-11-02 09:07 UTC, dmitrysadovskii commented on Valeria_Kondrateva/hw_9/task_9_1.py
> +            print('Книгу читает другой пользователь')
В данном случае от блока else можно избавить добавив assert проверку в начало метода на то что книга не зарезервирована.
Тогда book.reserved = True можно вынести за блок if в конец метода и так избавимся от дублирвоания кода

2022-11-02 09:07 UTC, dmitrysadovskii commented on Valeria_Kondrateva/hw_9/task_9_1.py
> +            print('Книга уже зарезервирована')
Тоже самое сделать что выше. Добавить ассерт и так избавимся от блока if

2022-11-02 09:07 UTC, dmitrysadovskii commented on Valeria_Kondrateva/hw_9/task_9_2.py
> +        self.rate = 0.1
Добавь в конструктора __init__ аргумент rate со значением по умолчанию 0.1

2022-11-03 07:41 UTC, llleeera commented
Исправила ошибки

2022-11-05 09:16 UTC, merged