Sergey_Zapashchykov: Homework9
dmitrysadovskii/QAP10 pull request #97
Opened 2022-10-26 21:50 UTC by SergeyZapashchykov

Задание готово к проверке.

2022-11-02 08:56 UTC, dmitrysadovskii requested changes
Хорошая домашка. Подправь комменты и можно мержить

2022-11-02 08:56 UTC, dmitrysadovskii commented on Sergey Zapashchykov/HW_9/task_9_1.py
> +            print(f"{book} can't be taken.")
В данном случае от блока if можно избавить добавив assert проверку в начало метода на то что книга доступна для того что бы взять и за ассертом добавляешь книгу в список книг пользователя

2022-11-02 08:56 UTC, dmitrysadovskii commented on Sergey Zapashchykov/HW_9/task_9_1.py
> +            print(f"You didn't take {book}")
Тоже самое что выше

2022-11-02 08:56 UTC, dmitrysadovskii commented on Sergey Zapashchykov/HW_9/task_9_2.py
> +    @classmethod
Почему решил сделать данный метом методом класса?

2022-11-07 08:22 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_9/task_9_1.py
> +            print(f"{book} can't be taken.")
Поправил, использовал assert.

2022-11-07 08:22 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_9/task_9_1.py
> +            print(f"You didn't take {book}")
Поправил, использовал assert.

2022-11-07 08:25 UTC, SergeyZapashchykov commented on Sergey Zapashchykov/HW_9/task_9_2.py
> +    @classmethod
Как мне показалось, нам нет необходимости создавать объект класса Bank, нам не нужен какой-то конкретный банк, чтобы посчитать результат. Также pycharm вывел предложение об объявлении в подсказках, это и натолкнуло на подумать.

2022-11-07 08:26 UTC, SergeyZapashchykov commented
Поправил комментарии.
Готово к проверке.

2022-11-10 05:31 UTC, merged